openapi: 3.0.0
info:
  title: Entertainment-web
  description: API
  version: 0.1.9

servers:
  - url: https://entertainment-web-app-back-production.up.railway.app/api/
  # description: production server
  - url: http://localhost:3000/api/
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /register:
    post:
      tags:
        - User
      requestBody:
        description: add the new user
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                firstName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                photo:
                  type: string
      responses:
        "201":
          description: new user
  /users:
    get:
      tags:
        - User
      responses:
        "200":
          description: get all users
    /login:
      post:
        tags:
          - User
        requestBody:
          description: user login request
          required: true
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          "201":
            description: user login successfully
    # /users/empty:
    # delete:
    # tags:
    #   - User
    # responses:
    # "200":
    # description: users table has been emptied
  /addMovie:
    post:
      tags:
        - Movie
      requestBody:
        description: add the new movie
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
                posterSmall:
                  type: string
                posterMedium:
                  type: string
                posterLarge:
                  type: string
                rating:
                  type: string
                year:
                  type: integer
      responses:
        "201":
          description: new movie
  /allMovies:
    get:
      tags:
        - Movie
      responses:
        "200":
          description: get all movies
  /addCategory:
    post:
      tags:
        - MovieCategory
      requestBody:
        description: add the new category
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                trending:
                  type: boolean
                recommended:
                  type: boolean
                tvSeries:
                  type: boolean
      responses:
        "201":
          description: new movie
  /allCategories:
    get:
      tags:
        - MovieCategory
      responses:
        "200":
          description: get all categories
