openapi: 3.0.0
info:
  title: Entertainment-web
  description: API
  version: 0.1.9

servers:
  - url: https://entertainment-web-app-back-production.up.railway.app/api/
  - url: http://localhost:3000/api/
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /register:
    post:
      tags:
        - User
      requestBody:
        description: add the new user
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                firstName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                photo:
                  type: string
                isVerified:
                  type: boolean
                  default: false # Default value set to false
      responses:
        "201":
          description: new user
        "400":
         description: Token not created
        "500":
         description: Internal server error
  /users:
    get:
      tags:
        - User
      responses:
        "200":
          description: get all users
  /login:
    post:
      tags:
        - User
      requestBody:
        description: user login request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: user login successfully
  /addMovie:
    post:
      tags:
        - Movie
      requestBody:
        description: add the new movie
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: string
                posterSmall:
                  type: string
                posterMedium:
                  type: string
                posterLarge:
                  type: string
                rating:
                  type: string
                year:
                  type: integer
      responses:
        "201":
          description: new movie
  /allMovies:
    get:
      tags:
        - Movie
      responses:
        "200":
          description: get all movies
  /addCategory:
    post:
      tags:
        - Category
      requestBody:
        description: add the new category
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
      responses:
        "201":
          description: new category
  /verify-email:
    get:
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: UserId
        - name: token
          in: path
          required: true
          schema:
            type: string
          description: token
      responses:
        "400":
          description: Your verification link may have expired. Please click on resend for verify your Email.
        "401":
          description: We were unable to find a user for this verification. Please SignUp
        "200":
          description: User has already been verified.Please Login
        "200":
          description: Your account has been successfully verified
